FROM docker.io/node:18.4.0 as builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

RUN ["npm", "run", "build"]

# shouldn't have latest as this is bad form for server
FROM docker.io/nginx:latest

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

COPY --from=builder /usr/src/app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

